package com.example.nasrallah.emojimessage;

import android.support.v7.app.AppCompatActivity;
import android.os.Bundle;
import android.widget.EditText;
import android.widget.ImageView;
import android.widget.TextView;
import android.widget.Toast;

public class Main2Activity extends AppCompatActivity {

    @Override
    protected void onCreate(Bundle savedInstanceState) {
        super.onCreate(savedInstanceState);
        setContentView(R.layout.activity_main2);
        ImageView image = (ImageView) findViewById(R.id.imageView5);
        TextView t =(TextView) findViewById(R.id.textView);
        String s = getIntent().getStringExtra("EXTRA_SESSION_ID");
if (s.equals("1")){

    image.setImageResource(R.drawable.love);
    Toast.makeText(getApplicationContext(),"LOVE",
            Toast.LENGTH_SHORT).show();
t.setText("Are you in love? You’ve finally seen the love of your life, congratulation for finding that special " +
        "person that is giving your " +
        "life a new meaning. Keeping the" +
        " sparkling generated by your love " +
        "in everyday can sometimes seem difficult" +
        " especially when you want to please him or" +
        " her every now and then with your own time and commitment." +

        "<><><><>text your lover now with this message<<<<<< Sometimes, caring is better than loving. Sometimes, tea is better than coffee. Sometimes, smile is better than laughter, but nobody is better than you, finding time to text me.>>>>");
}
else if (s.equals("2"))
{
    image.setImageResource(R.drawable.haha);
    Toast.makeText(getApplicationContext(),"HaHa",
            Toast.LENGTH_SHORT).show();
    t.setText("1 - [Humanity] has unquestionably one really effective weapon—laughter. Power, money, persuasion, supplication, persecution—these can lift at a colossal humbug—push it a little—weaken it a little, century by century, but only laughter can blow it to rags and atoms at a blast. Against the assault of laughter nothing can stand. — Mark Twain\n" +
            "\n2 - A good laugh heals a lot of hurts. — Madeleine L’Engle\n\n" +
            "3 - A good laugh is a mighty good thing, a rather too scarce a good thing. — Herman Melville\n\n" +
            "4 - A good laugh is sunshine in the house. — William Thackeray\n\n" +
            "5 - A smile is a curve that sets everything straight. — Phyllis Diller\n\n" +
            "6 - A smile starts on the lips, a grin spreads to the eyes, a chuckle comes from the belly; but a good laugh bursts forth from the soul, overflows, and bubbles all around. — Carolyn Birmingham \n\n" +
            "7 - A well-balanced person is one who finds both sides of an issue laughable. — Herbert Procknow\n\n" +
            "8 - Against the assault of laughter, nothing can stand. — Mark Twain\n\n" +
            "9 - Always laugh when you can. It is cheap medicine. — Lord Byron\n\n" +
            "10 - Among those whom I like or admire, I can find no common denominator, but among those whom I love, I can: all of them make me laugh. — W. H. Auden");
        }
else if (s.equals("3"))
{
    image.setImageResource(R.drawable.sad);
    Toast.makeText(getApplicationContext(),"SAD",
            Toast.LENGTH_SHORT).show();
    t.setText("1 -  “I am aware that you are going through a difficult time right now, but I want to tell you that I know you and that you have come out of worse situations. Do not let these difficult times defeat you, remember that problems go away and we move on eventually. “ \n\n" +
            "2 - “Stop saying that the past was better as life is full of new opportunities and many surprises. You have to be aware in order to receive what life has to offer you and not just think of a past that will never come back. Be strong dear friend! “ \n\n" +
            "3 -  “Dear friend, do not forget that every day does not always go the way you want it to, but that after a rainy day, the sun always come out. Just be patient and learn what you can from these difficult times. Do not forget your good friends will always be there for you whenever you need them. “\n\n" +
            "4 -  “True friends are always by our side in the worst and the best of times, so do not think that you are alone right now, you have all of us. Do not forget that you will always find in me a friend you can turn to for anything, you can count on me. “\n\n" +
            "5 - “Dear friend. I understand you are going through a very difficult moment right now, but I want you to know that I am here for you, for whatever you need and to help you overcome this. “");
}
else if (s.equals("4"))
{
    image.setImageResource(R.drawable.angry);
    Toast.makeText(getApplicationContext(),"Angry",
            Toast.LENGTH_SHORT).show();
    t.setText("1) Anger is like a flame on a candle. The candle thinks that its flame is blazing powerful light, but it is actually the reason for its own meltdown.\n\n" +
            "2) Sometimes the cost of an impulsive and angry reaction can be so large that you wouldn’t able to buy your words or actions back even if you were a billionaire.\n\n" +
            "3) When you can’t take charge and control your anger, your anger will inevitably take control of you. Lesson to learn – control your anger before it controls you.\n\n" +
            "4) You can channel your anger positively to gain high focus and concentration. You can also channel your anger negatively to create damage and destruction. Whichever way you do, always remember that it is your own doing – don’t blame anything on anger.\n\n" +
            "5) ANGER actually means Atrocity, Negativity, Greif, Exhaustion and Regret. Convert that ANGER into Assertiveness, Niceness, Goodness, Eagerness and Righteousness.\n\n" +
            "6) Nursing a rage and a fire in the belly to change the world to make it a better place to live is the best and only type of anger you should have.\n\n" +
            "7) If kicking the wall helps you extinguish your anger, do it. It is easier to repair a broken wall than to mend a broken relationship.\n\n" +
            "8) Just because you have money in your bank, you shouldn’t spend it all the time. Just because you have an emotion called anger in your heart, you shouldn’t use it all the time.\n\n" +

            "9) You become angry when you lose your temper. You lose your senses when you lose your temper. You do crazy things when you are not in your senses. You make mistakes when you do crazy things. You regret when you make mistakes. Why do you want to be angry, only to regret later?\n\n" +


            "10) Anger is one of the greatest tests of friendship. If your friend can tolerate your anger, you must be willing to tolerate anything for your friend.");
}
    }
}
